# Generated by Django 5.2.9 on 2025-12-21 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('name', models.CharField(max_length=100)),
                ('referral_source', models.CharField(choices=[('twitter', 'Twitter/X'), ('github', 'GitHub'), ('friend', 'Friend/Colleague'), ('blog', 'Tech Blog'), ('other', 'Other')], default='other', max_length=20)),
                ('wants_updates', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Waitlist User',
                'verbose_name_plural': 'Waitlist Users',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
